"""
=============================================================================
ms_buildings_urban_bcr.py — MS Buildings Urban Agglomeration BCR
Paper: Benchmarking Open Geospatial Data Stacks
=============================================================================
Extracts Microsoft Buildings urban agglomeration BCR from the three-way
completeness grids already generated by 06_ms_buildings_bcr.py.

The three-way grid encodes:
  0   = data gap (GHSL built-up, neither dataset)
  1   = Overture Maps only
  2   = Microsoft Buildings only
  3   = both datasets
  255 = nodata (non-built-up)

The urban extent is derived from GHSL-SMOD (same method as Overture urban BCR).
For each country:
  - Load the three-way grid
  - Load the GHSL-SMOD urban extent
  - Mask the grid to urban extent pixels
  - Count cells where value is 2 (MS only) or 3 (both) — i.e., MS Buildings present
  - Urban MS BCR = (cells with MS present) / (all built-up urban cells) * 100

This produces the missing column for Table 4 in the manuscript.

USAGE
─────
  python 08_ms_buildings_urban_bcr.py
=============================================================================
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import rasterio
from rasterio.mask import mask as rio_mask
from shapely.geometry import mapping

sys.path.insert(0, str(Path(__file__).parent))

from analysis_config import COUNTRIES, GRID_DIR, TABLE_DIR
from data_loader import get_urban_extent


def compute_ms_urban_bcr(iso3: str) -> dict:
    """
    Extract MS Buildings urban BCR from the three-way completeness grid.

    In the three-way grid:
      MS Buildings present = cell value 2 OR 3 (bit 2 is set)
      GHSL built-up cell   = any value 0,1,2,3 (255 = nodata/non-built-up)

    Urban MS BCR = (n built-up urban cells with MS present) /
                  (n built-up urban cells total) * 100
    """
    grid_path = GRID_DIR / f"{iso3}_bcr_100m_threeway.tif"
    if not grid_path.exists():
        print(f"  ✗ {iso3}: three-way grid not found at {grid_path}")
        return {"iso3": iso3, "bcr_ms_urban_pct": None}

    # Get urban extent (WGS84 polygon)
    try:
        urban_gdf  = get_urban_extent(iso3)
        urban_geom = urban_gdf.geometry.unary_union
    except Exception as e:
        print(f"  ✗ {iso3}: urban extent failed: {e}")
        return {"iso3": iso3, "bcr_ms_urban_pct": None}

    with rasterio.open(grid_path) as src:
        raster_crs = src.crs

        # Reproject urban extent to raster CRS if needed
        if str(raster_crs).upper() not in ("EPSG:4326", "CRS84"):
            from pyproj import Transformer
            from shapely.ops import transform as shp_transform
            transformer = Transformer.from_crs(
                "EPSG:4326", str(raster_crs), always_xy=True
            )
            urban_geom_proj = shp_transform(transformer.transform, urban_geom)
        else:
            urban_geom_proj = urban_geom

        try:
            urban_data, _ = rio_mask(
                src, [mapping(urban_geom_proj)], crop=True, filled=True
            )
            urban_grid = urban_data[0]
        except Exception as e:
            print(f"  ⚠ {iso3}: raster mask failed ({e}), using full grid")
            urban_grid = src.read(1)

    # Built-up urban cells = values 0, 1, 2, 3 (exclude 255 = nodata)
    buildup_mask = urban_grid < 255
    n_buildup    = int(buildup_mask.sum())

    if n_buildup == 0:
        print(f"  ✗ {iso3}: no built-up urban cells found")
        return {"iso3": iso3, "bcr_ms_urban_pct": None, "n_ghsl_urban": 0}

    # MS Buildings present = value 2 (MS only) OR value 3 (both)
    # Bit check: value & 2 > 0
    ms_present = ((urban_grid == 2) | (urban_grid == 3)) & buildup_mask
    n_ms       = int(ms_present.sum())

    # Overture present = value 1 (Overture only) OR value 3 (both)
    ov_present = ((urban_grid == 1) | (urban_grid == 3)) & buildup_mask
    n_ov       = int(ov_present.sum())

    ms_urban_bcr = round(n_ms / n_buildup * 100, 2)
    ov_urban_bcr = round(n_ov / n_buildup * 100, 2)

    # Cross-check: Overture urban BCR should match the previously computed value
    result = {
        "iso3":                    iso3,
        "country":                 COUNTRIES[iso3]["name"],
        "n_ghsl_urban_cells":      n_buildup,
        "n_ms_urban_covered":      n_ms,
        "n_ov_urban_covered":      n_ov,
        "bcr_ms_urban_pct":        ms_urban_bcr,
        "bcr_ov_urban_pct_check":  ov_urban_bcr,  # cross-check vs Table 4
    }

    print(f"  ✓ {iso3}: MS urban BCR = {ms_urban_bcr:.1f}%  "
          f"(Overture urban BCR check = {ov_urban_bcr:.1f}%)")
    return result


def run_ms_urban_bcr_all() -> pd.DataFrame:
    """
    Compute MS Buildings urban BCR for all seven countries and save.
    """
    print("\n" + "="*60)
    print("  MS BUILDINGS URBAN BCR — ALL COUNTRIES")
    print("="*60)

    results = []
    for iso3 in COUNTRIES:
        print(f"\n── {COUNTRIES[iso3]['name']} ({iso3}) ──")
        row = compute_ms_urban_bcr(iso3)
        results.append(row)

    df = pd.DataFrame(results)

    # Merge with existing MS BCR national results for complete table
    ms_national_path = TABLE_DIR / "ms_buildings_bcr.csv"
    if ms_national_path.exists():
        ms_nat = pd.read_csv(ms_national_path)
        df = df.merge(
            ms_nat[["iso3", "n_ms_buildings", "bcr_ms_national_pct"]],
            on="iso3", how="left"
        )

    out_path = TABLE_DIR / "ms_buildings_urban_bcr.csv"
    df.to_csv(out_path, index=False)
    print(f"\n✓ MS Buildings urban BCR saved: {out_path}")

    print("\nSummary:")
    print("-"*55)
    cols = ["iso3", "country", "bcr_ms_national_pct", "bcr_ms_urban_pct",
            "bcr_ov_urban_pct_check"]
    cols = [c for c in cols if c in df.columns]
    print(df[cols].to_string(index=False))

    return df


if __name__ == "__main__":
    run_ms_urban_bcr_all()
